### ISSUE TITLE
Failed to pip install because of a setup.py issue

### ISSUE THREAD

**Issue by leonmax** [aliyun/alibabacloud-python-sdk-v2#28]
安装失败，问题出在setup.py需要import __version__，在load __init__.py的时候层层调用，已经import了jmespath，但因为setup.py没读完，系统也没机会安装jmespath作为dependency
```
pip install alibaba-cloud-python-sdk-v2                             1945ms
Looking in indexes: https://artifact.rd.inceptioglobal.ai/artifactory/api/pypi/pypi/simple, https://pypi.org/simple
Collecting alibaba-cloud-python-sdk-v2
  Using cached https://artifact.rd.inceptioglobal.ai/artifactory/api/pypi/pypi/packages/packages/6a/67/0244b84f93699e67af65bd18d79c090f09cb1af7c2f363586440190dd6c6/alibaba-cloud-python-sdk-v2-1.0.6.tar.gz (793 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/leonmax/test/.direnv/python-3.7.7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8k/3hly_5h16_ndhnfdzd3vtgfm0000gn/T/pip-install-8czuwtdv/alibaba-cloud-python-sdk-v2/setup.py'"'"'; __file__='"'"'/private/var/folders/8k/3hly_5h16_ndhnfdzd3vtgfm0000gn/T/pip-install-8czuwtdv/alibaba-cloud-python-sdk-v2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/8k/3hly_5h16_ndhnfdzd3vtgfm0000gn/T/pip-pip-egg-info-vqtjz47m
         cwd: /private/var/folders/8k/3hly_5h16_ndhnfdzd3vtgfm0000gn/T/pip-install-8czuwtdv/alibaba-cloud-python-sdk-v2/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8k/3hly_5h16_ndhnfdzd3vtgfm0000gn/T/pip-install-8czuwtdv/alibaba-cloud-python-sdk-v2/setup.py", line 19, in <module>
        VERSION = __import__("alibabacloud").__version__
      File "/private/var/folders/8k/3hly_5h16_ndhnfdzd3vtgfm0000gn/T/pip-install-8czuwtdv/alibaba-cloud-python-sdk-v2/alibabacloud/__init__.py", line 20, in <module>
        from alibabacloud.client import ClientConfig
      File "/private/var/folders/8k/3hly_5h16_ndhnfdzd3vtgfm0000gn/T/pip-install-8czuwtdv/alibaba-cloud-python-sdk-v2/alibabacloud/client.py", line 21, in <module>
        import alibabacloud.retry.retry_policy as retry_policy
      File "/private/var/folders/8k/3hly_5h16_ndhnfdzd3vtgfm0000gn/T/pip-install-8czuwtdv/alibaba-cloud-python-sdk-v2/alibabacloud/retry/retry_policy.py", line 15, in <module>
        from alibabacloud.retry.retry_condition import *
      File "/private/var/folders/8k/3hly_5h16_ndhnfdzd3vtgfm0000gn/T/pip-install-8czuwtdv/alibaba-cloud-python-sdk-v2/alibabacloud/retry/retry_condition.py", line 15, in <module>
        import jmespath
    ModuleNotFoundError: No module named 'jmespath'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by leonmax** [comment]
这个项目还活着吗？5个月没动了。我主要需要credential chain部分，openapi的那个python sdk并没有credential chain
